# Server Network Settings
server.port=${PORT:8080}
server.address=0.0.0.0

# FitConnect Database Connection (Supabase / Render Database)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://aws-0-eu-west-1.pooler.supabase.com:5432/postgres}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres.otkmywwdyrjtqqwqterp}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:<FIT-CONNECT2026>}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Security Settings
jwt.secret=${JWT_SECRET:FitConnectSuperSecretKeyForJwtGenerationMustBeLongEnough}

# AI Integration
gemini.api.key=${GEMINI_API_KEY:AQ.Ab8RN6KriFaYb-xwlT2uQsgUcnvlQCgoBCUjVcYHebwWJi-s-w}

# Payment Integration
paystack.secret.key=${PAYSTACK_SECRET_KEY:sk_test_1f297f9c15bab144d5b36885d0d08a1c6aa77040}

# Gmail SMTP Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:agbekoelorm32@gmail.com}
spring.mail.password=${MAIL_PASSWORD:nkvfgvpcxxxzuirx}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000